### PR TITLE
#345 Sonarqube new LTS 9.9 support

### LINKED ISSUE #345: Sonarqube new LTS 9.9 support
Hello, there is a new LTS version of sonarqube.

I'll try to take some time to help you to make the update, but I'm still creating the issue in order to trace it :)

### PR DESCRIPTION
**Pull request by theljade**
## Proposed changes

Update of all sonarqube dependencies to be compatible with de last sonarqube LTS 9.9.*
I also updated all dependencies to the last version (except poi-ooxml and slf4j which are breaking).
The last sonar-ws dependency is not anymore compatible with java 8, then I had to delete the java 8 continious integration test.

## Types of changes

What types of changes does your code introduce to this software?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Issues closed by changes

- [x] Close #345 

## Checklist

> _Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/cnescatlab/sonar-cnes-report/blob/master/CONTRIBUTING.md) doc
- [x] I agree with the [CODE OF CONDUCT](https://github.com/cnescatlab/sonar-cnes-report/blob/master/CONTRIBUTING.md)
- [x] Lint and unit tests pass locally with my changes
- [x] SonarCloud and Travis CI tests pass with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by braisvq1996** [comment]
Hi @theljade I am not a member of this organization at all but I am also interested in the support for SonarQube 9.9.x LTS
For the tests should this [line ](https://github.com/cnescatlab/sonar-cnes-report/blob/master/.github/workflows/java-continuous-integration.yml#L46)not be updated ?

**Comment by theljade** [comment]
> Hi @theljade I am not a member of this organization at all but I am also interested in the support for SonarQube 9.9.x LTS For the tests should this [line ](https://github.com/cnescatlab/sonar-cnes-report/blob/master/.github/workflows/java-continuous-integration.yml#L46)not be updated ? (even if you cannot run the github actions until someone approve it for you...)

Yes i did :) https://github.com/theljade/sonar-cnes-report/blob/master/.github/workflows/java-continuous-integration.yml#L46 
You are just looking on the bad repository

**Comment by braisvq1996** [comment]
You are right @theljade, my bad

**Comment by wizpresso-steve-cy-fan** [comment]
@louisjdmartin would you like to review?

**Comment by louisjdmartin** [comment]
@wizpresso-steve-cy-fan we are currently working on upgrading the CNES-Report to make it compatible with SonarQube 9.9LTS (in order to also upgrade docker-cat to 9.9 also)

@diegorodriguez31 you may take a look at this PR

**Comment by wizpresso-steve-cy-fan** [comment]
@diegorodriguez31 I did not test the plugin mode but it works externally with 9.9 Community

**Comment by Silicoman** [comment]
Hi,

i have compiled locally the project and i have deployed on SonarQube Enterprise Edition Version 9.9 (build 65466)
I have the cnesreport tab and export seem working good. 

Thank for your contribution.

image

**Comment by diegorodriguez31** [comment]
Thank you for all your contribution. I close de MR but a new one is opened with our changes.

**Pull request closed without merging**
